#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T_Speich_CPT_206_Lab_3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StateDB")]
	public partial class StateDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTATE(STATE instance);
    partial void UpdateSTATE(STATE instance);
    partial void DeleteSTATE(STATE instance);
    partial void InsertSTATE_LARGEST_CITY(STATE_LARGEST_CITY instance);
    partial void UpdateSTATE_LARGEST_CITY(STATE_LARGEST_CITY instance);
    partial void DeleteSTATE_LARGEST_CITY(STATE_LARGEST_CITY instance);
    #endregion
		
		public StateDBDataContext() : 
				base(global::T_Speich_CPT_206_Lab_3.Properties.Settings.Default.StateDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public StateDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StateDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StateDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StateDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STATE> STATEs
		{
			get
			{
				return this.GetTable<STATE>();
			}
		}
		
		public System.Data.Linq.Table<STATE_LARGEST_CITY> STATE_LARGEST_CITies
		{
			get
			{
				return this.GetTable<STATE_LARGEST_CITY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STATE")]
	public partial class STATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STATE_ID;
		
		private string _STATE_NAME;
		
		private int _STATE_POPULATION;
		
		private string _STATE_FLAG_DESC;
		
		private string _STATE_COLORS;
		
		private string _STATE_BIRD;
		
		private string _STATE_FLOWER;
		
		private string _STATE_CAPITOL;
		
		private System.Nullable<decimal> _STATE_MEDIAN_INCOME;
		
		private System.Nullable<decimal> _STATE_IT_JOB_PERCENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTATE_IDChanging(int value);
    partial void OnSTATE_IDChanged();
    partial void OnSTATE_NAMEChanging(string value);
    partial void OnSTATE_NAMEChanged();
    partial void OnSTATE_POPULATIONChanging(int value);
    partial void OnSTATE_POPULATIONChanged();
    partial void OnSTATE_FLAG_DESCChanging(string value);
    partial void OnSTATE_FLAG_DESCChanged();
    partial void OnSTATE_COLORSChanging(string value);
    partial void OnSTATE_COLORSChanged();
    partial void OnSTATE_BIRDChanging(string value);
    partial void OnSTATE_BIRDChanged();
    partial void OnSTATE_FLOWERChanging(string value);
    partial void OnSTATE_FLOWERChanged();
    partial void OnSTATE_CAPITOLChanging(string value);
    partial void OnSTATE_CAPITOLChanged();
    partial void OnSTATE_MEDIAN_INCOMEChanging(System.Nullable<decimal> value);
    partial void OnSTATE_MEDIAN_INCOMEChanged();
    partial void OnSTATE_IT_JOB_PERCENTChanging(System.Nullable<decimal> value);
    partial void OnSTATE_IT_JOB_PERCENTChanged();
    #endregion
		
		public STATE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STATE_ID
		{
			get
			{
				return this._STATE_ID;
			}
			set
			{
				if ((this._STATE_ID != value))
				{
					this.OnSTATE_IDChanging(value);
					this.SendPropertyChanging();
					this._STATE_ID = value;
					this.SendPropertyChanged("STATE_ID");
					this.OnSTATE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this.OnSTATE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._STATE_NAME = value;
					this.SendPropertyChanged("STATE_NAME");
					this.OnSTATE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_POPULATION", DbType="Int NOT NULL")]
		public int STATE_POPULATION
		{
			get
			{
				return this._STATE_POPULATION;
			}
			set
			{
				if ((this._STATE_POPULATION != value))
				{
					this.OnSTATE_POPULATIONChanging(value);
					this.SendPropertyChanging();
					this._STATE_POPULATION = value;
					this.SendPropertyChanged("STATE_POPULATION");
					this.OnSTATE_POPULATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_FLAG_DESC", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string STATE_FLAG_DESC
		{
			get
			{
				return this._STATE_FLAG_DESC;
			}
			set
			{
				if ((this._STATE_FLAG_DESC != value))
				{
					this.OnSTATE_FLAG_DESCChanging(value);
					this.SendPropertyChanging();
					this._STATE_FLAG_DESC = value;
					this.SendPropertyChanged("STATE_FLAG_DESC");
					this.OnSTATE_FLAG_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_COLORS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string STATE_COLORS
		{
			get
			{
				return this._STATE_COLORS;
			}
			set
			{
				if ((this._STATE_COLORS != value))
				{
					this.OnSTATE_COLORSChanging(value);
					this.SendPropertyChanging();
					this._STATE_COLORS = value;
					this.SendPropertyChanged("STATE_COLORS");
					this.OnSTATE_COLORSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_BIRD", DbType="NVarChar(50)")]
		public string STATE_BIRD
		{
			get
			{
				return this._STATE_BIRD;
			}
			set
			{
				if ((this._STATE_BIRD != value))
				{
					this.OnSTATE_BIRDChanging(value);
					this.SendPropertyChanging();
					this._STATE_BIRD = value;
					this.SendPropertyChanged("STATE_BIRD");
					this.OnSTATE_BIRDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_FLOWER", DbType="NVarChar(50)")]
		public string STATE_FLOWER
		{
			get
			{
				return this._STATE_FLOWER;
			}
			set
			{
				if ((this._STATE_FLOWER != value))
				{
					this.OnSTATE_FLOWERChanging(value);
					this.SendPropertyChanging();
					this._STATE_FLOWER = value;
					this.SendPropertyChanged("STATE_FLOWER");
					this.OnSTATE_FLOWERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CAPITOL", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STATE_CAPITOL
		{
			get
			{
				return this._STATE_CAPITOL;
			}
			set
			{
				if ((this._STATE_CAPITOL != value))
				{
					this.OnSTATE_CAPITOLChanging(value);
					this.SendPropertyChanging();
					this._STATE_CAPITOL = value;
					this.SendPropertyChanged("STATE_CAPITOL");
					this.OnSTATE_CAPITOLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_MEDIAN_INCOME", DbType="Money")]
		public System.Nullable<decimal> STATE_MEDIAN_INCOME
		{
			get
			{
				return this._STATE_MEDIAN_INCOME;
			}
			set
			{
				if ((this._STATE_MEDIAN_INCOME != value))
				{
					this.OnSTATE_MEDIAN_INCOMEChanging(value);
					this.SendPropertyChanging();
					this._STATE_MEDIAN_INCOME = value;
					this.SendPropertyChanged("STATE_MEDIAN_INCOME");
					this.OnSTATE_MEDIAN_INCOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_IT_JOB_PERCENT", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> STATE_IT_JOB_PERCENT
		{
			get
			{
				return this._STATE_IT_JOB_PERCENT;
			}
			set
			{
				if ((this._STATE_IT_JOB_PERCENT != value))
				{
					this.OnSTATE_IT_JOB_PERCENTChanging(value);
					this.SendPropertyChanging();
					this._STATE_IT_JOB_PERCENT = value;
					this.SendPropertyChanged("STATE_IT_JOB_PERCENT");
					this.OnSTATE_IT_JOB_PERCENTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STATE_LARGEST_CITY")]
	public partial class STATE_LARGEST_CITY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STATE_ID;
		
		private string _LARGEST_CITY;
		
		private string _SECOND_LARGEST_CITY;
		
		private string _THIRD_LARGEST_CITY;
		
		private EntityRef<STATE> _STATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTATE_IDChanging(int value);
    partial void OnSTATE_IDChanged();
    partial void OnLARGEST_CITYChanging(string value);
    partial void OnLARGEST_CITYChanged();
    partial void OnSECOND_LARGEST_CITYChanging(string value);
    partial void OnSECOND_LARGEST_CITYChanged();
    partial void OnTHIRD_LARGEST_CITYChanging(string value);
    partial void OnTHIRD_LARGEST_CITYChanged();
    #endregion
		
		public STATE_LARGEST_CITY()
		{
			this._STATE = default(EntityRef<STATE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int STATE_ID
		{
			get
			{
				return this._STATE_ID;
			}
			set
			{
				if ((this._STATE_ID != value))
				{
					if (this._STATE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSTATE_IDChanging(value);
					this.SendPropertyChanging();
					this._STATE_ID = value;
					this.SendPropertyChanged("STATE_ID");
					this.OnSTATE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LARGEST_CITY", DbType="NVarChar(50)")]
		public string LARGEST_CITY
		{
			get
			{
				return this._LARGEST_CITY;
			}
			set
			{
				if ((this._LARGEST_CITY != value))
				{
					this.OnLARGEST_CITYChanging(value);
					this.SendPropertyChanging();
					this._LARGEST_CITY = value;
					this.SendPropertyChanged("LARGEST_CITY");
					this.OnLARGEST_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECOND_LARGEST_CITY", DbType="NVarChar(50)")]
		public string SECOND_LARGEST_CITY
		{
			get
			{
				return this._SECOND_LARGEST_CITY;
			}
			set
			{
				if ((this._SECOND_LARGEST_CITY != value))
				{
					this.OnSECOND_LARGEST_CITYChanging(value);
					this.SendPropertyChanging();
					this._SECOND_LARGEST_CITY = value;
					this.SendPropertyChanged("SECOND_LARGEST_CITY");
					this.OnSECOND_LARGEST_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THIRD_LARGEST_CITY", DbType="NVarChar(50)")]
		public string THIRD_LARGEST_CITY
		{
			get
			{
				return this._THIRD_LARGEST_CITY;
			}
			set
			{
				if ((this._THIRD_LARGEST_CITY != value))
				{
					this.OnTHIRD_LARGEST_CITYChanging(value);
					this.SendPropertyChanging();
					this._THIRD_LARGEST_CITY = value;
					this.SendPropertyChanged("THIRD_LARGEST_CITY");
					this.OnTHIRD_LARGEST_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STATE_STATE_LARGEST_CITY", Storage="_STATE", ThisKey="STATE_ID", OtherKey="STATE_ID", IsForeignKey=true)]
		public STATE STATE
		{
			get
			{
				return this._STATE.Entity;
			}
			set
			{
				if ((this._STATE.Entity != value))
				{
					this.SendPropertyChanging();
					this._STATE.Entity = value;
					this.SendPropertyChanged("STATE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
